[deps]
Arpack = "7d9fca2a-8960-54d3-9f78-7d1dccf2cb97"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
Quadmath = "be4d8f0f-7fa4-5f49-b795-2f01399ab2dd"
